In [1]:
import requests
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import html5lib
from fake_useragent import UserAgent

nba_teams = {
    'Miami Heat': 'MIA',
    'Chicago Bulls': 'CHI',
    'Philadelphia 76ers': 'PHI',
    'New Jersey Nets': 'NJN',
    'Golden State Warriors': 'GSW',
    'Boston Celtics': 'BOS',
    'Indiana Pacers': 'IND',
    'Atlanta Hawks': 'ATL',
    'New York Knicks': 'NYK',
    'Toronto Raptors': 'TOR',
    'Cleveland Cavaliers': 'CLE',
    'Orlando Magic': 'ORL',
    'Phoenix Suns': 'PHO',
    'Denver Nuggets': 'DEN',
    'Houston Rockets': 'HOU',
    'Minnesota Timberwolves': 'MIN',
    'San Antonio Spurs': 'SAS',
    'Portland Trail Blazers': 'POR',
    'Sacramento Kings': 'SAC',
    'Charlotte Hornets': 'CHH',
    'Detroit Pistons': 'DET',
    'Dallas Mavericks': 'DAL',
    'Seattle SuperSonics': 'SEA',
    'Vancouver Grizzlies': 'VAN',
    'Los Angeles Lakers': 'LAL',
    'Los Angeles Clippers': 'LAC',
    'Utah Jazz': 'UTA',
    'Washington Wizards': 'WAS',
    'Milwaukee Bucks': 'MIL',
    'Memphis Grizzlies': 'MEM',
    'New Orleans Hornets': 'NOH',
    'New Orleans/Oklahoma City Hornets': 'NOK',
    'Oklahoma City Thunder': 'OKC',
    'Brooklyn Nets': 'BRK',
    'New Orleans Pelicans': 'NOP',
    'Charlotte Bobcats': 'CHO',
    'New Charlotte Hornets': 'CHA'
}

# Function to check if the webpage exists
def page_not_exists(url):
    response = requests.get(url)
    return response.status_code == 404

def get_bballref_records_df(url, team, season, retry_count = 0, max_retries = 3):
    time.sleep(3.68)
    
    # Get the page request
    #ua = UserAgent()
    #headers = {'User-Agent': ua.random}
    #response = requests.get(url, headers=headers)
    
    response = requests.get(url)
    
    # Parse the page with BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Try to find the 'roster' table directly, and specify the class or ID to narrow down the search
    table = soup.find('table', {'id': 'games'})
    if table is None:
        # Check if retry count has exceeded max retries
        if retry_count >= max_retries:
            print(f"Max retries reached for {team} in {season}. Moving to the next team.")
            return None
        
        print(f"No 'games' table found for {team} in {season}. Retrying...")
        return get_bballref_records_df(url, team, season, retry_count + 1, max_retries)

    # Read the table into a DataFrame
    try:
        df = pd.read_html(str(table))[0]  # Convert HTML table to DataFrame
    except ValueError:
        print(f"Error: Could not parse the table for {team} in {season}.")
        return None

    # Clean the DataFrame as needed
    df = df.rename(columns = {'Unnamed: 7': 'Result'})
    df = df[df['Date'] != 'Date']
    df = df.drop(columns = ['G', 'Date', 'Start (ET)', 'Tm', 'Opp', 'W', 'L', 'Streak', 'Attend.', 'LOG', 'Notes'])
    df = df.drop(columns = [col for col in df.columns if 'Unnamed' in col])
    
    print(f"Found table for {team} in {season}.")
    
    return df

In [2]:
seasons = ['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
game_log_dfs = {}
for season in seasons:
    for team in nba_teams.values():
        url = f'https://www.basketball-reference.com/teams/{team}/{season}_games.html'
        if page_not_exists(url):
            print(f"Page not found for {team} in {season}. Skipping...")
            time.sleep(3.68)
            continue
        # Fetch the data if the page exists
        df = get_bballref_records_df(url, team, season)
        game_log_dfs[season+team] = df

Found table for MIA in 2001.
Found table for CHI in 2001.
Found table for PHI in 2001.
Found table for NJN in 2001.
Found table for GSW in 2001.
Found table for BOS in 2001.
Found table for IND in 2001.
Found table for ATL in 2001.
Found table for NYK in 2001.
Found table for TOR in 2001.
Found table for CLE in 2001.
Found table for ORL in 2001.
Found table for PHO in 2001.
Found table for DEN in 2001.
Found table for HOU in 2001.
Found table for MIN in 2001.
Found table for SAS in 2001.
Found table for POR in 2001.
Found table for SAC in 2001.
Found table for CHH in 2001.
Found table for DET in 2001.
Found table for DAL in 2001.
Found table for SEA in 2001.
Found table for VAN in 2001.
Found table for LAL in 2001.
Found table for LAC in 2001.
Found table for UTA in 2001.
Found table for WAS in 2001.
Found table for MIL in 2001.
Page not found for MEM in 2001. Skipping...
Page not found for NOH in 2001. Skipping...
Page not found for NOK in 2001. Skipping...
Page not found for OKC in 2001. Skipping...
Page not found for BRK in 2001. Skipping...
Page not found for NOP in 2001. Skipping...
Page not found for CHO in 2001. Skipping...
Page not found for CHA in 2001. Skipping...
Found table for MIA in 2002.
Found table for CHI in 2002.
Found table for PHI in 2002.
Found table for NJN in 2002.
Found table for GSW in 2002.
Found table for BOS in 2002.
Found table for IND in 2002.
Found table for ATL in 2002.
Found table for NYK in 2002.
Found table for TOR in 2002.
Found table for CLE in 2002.
Found table for ORL in 2002.
Found table for PHO in 2002.
Found table for DEN in 2002.
Found table for HOU in 2002.
Found table for MIN in 2002.
Found table for SAS in 2002.
Found table for POR in 2002.
Found table for SAC in 2002.
Found table for CHH in 2002.
Found table for DET in 2002.
Found table for DAL in 2002.
Found table for SEA in 2002.
Page not found for VAN in 2002. Skipping...
Found table for LAL in 2002.
Found table for LAC in 2002.
Found table for UTA in 2002.
Found table for WAS in 2002.
Found table for MIL in 2002.
Found table for MEM in 2002.
Page not found for NOH in 2002. Skipping...
Page not found for NOK in 2002. Skipping...
Page not found for OKC in 2002. Skipping...
Page not found for BRK in 2002. Skipping...
Page not found for NOP in 2002. Skipping...
Page not found for CHO in 2002. Skipping...
Page not found for CHA in 2002. Skipping...
Found table for MIA in 2003.
Found table for CHI in 2003.
Found table for PHI in 2003.
Found table for NJN in 2003.
Found table for GSW in 2003.
Found table for BOS in 2003.
Found table for IND in 2003.
Found table for ATL in 2003.
Found table for NYK in 2003.
Found table for TOR in 2003.
Found table for CLE in 2003.
Found table for ORL in 2003.
Found table for PHO in 2003.
Found table for DEN in 2003.
Found table for HOU in 2003.
Found table for MIN in 2003.
Found table for SAS in 2003.
Found table for POR in 2003.
Found table for SAC in 2003.
Page not found for CHH in 2003. Skipping...
Found table for DET in 2003.
Found table for DAL in 2003.
Found table for SEA in 2003.
Page not found for VAN in 2003. Skipping...
Found table for LAL in 2003.
Found table for LAC in 2003.
Found table for UTA in 2003.
Found table for WAS in 2003.
Found table for MIL in 2003.
Found table for MEM in 2003.
Found table for NOH in 2003.
Page not found for NOK in 2003. Skipping...
Page not found for OKC in 2003. Skipping...
Page not found for BRK in 2003. Skipping...
Page not found for NOP in 2003. Skipping...
Page not found for CHO in 2003. Skipping...
Page not found for CHA in 2003. Skipping...
Found table for MIA in 2004.
Found table for CHI in 2004.
Found table for PHI in 2004.
Found table for NJN in 2004.
Found table for GSW in 2004.
Found table for BOS in 2004.
Found table for IND in 2004.
Found table for ATL in 2004.
Found table for NYK in 2004.
Found table for TOR in 2004.
Found table for CLE in 2004.
Found table for ORL in 2004.
Found table for PHO in 2004.
Found table for DEN in 2004.
Found table for HOU in 2004.
Found table for MIN in 2004.
Found table for SAS in 2004.
Found table for POR in 2004.
Found table for SAC in 2004.
Page not found for CHH in 2004. Skipping...
Found table for DET in 2004.
Found table for DAL in 2004.
Found table for SEA in 2004.
Page not found for VAN in 2004. Skipping...
Found table for LAL in 2004.
Found table for LAC in 2004.
Found table for UTA in 2004.
Found table for WAS in 2004.
Found table for MIL in 2004.
Found table for MEM in 2004.
Found table for NOH in 2004.
Page not found for NOK in 2004. Skipping...
Page not found for OKC in 2004. Skipping...
Page not found for BRK in 2004. Skipping...
Page not found for NOP in 2004. Skipping...
Page not found for CHO in 2004. Skipping...
Page not found for CHA in 2004. Skipping...
Found table for MIA in 2005.
Found table for CHI in 2005.
Found table for PHI in 2005.
Found table for NJN in 2005.
Found table for GSW in 2005.
Found table for BOS in 2005.
Found table for IND in 2005.
Found table for ATL in 2005.
Found table for NYK in 2005.
Found table for TOR in 2005.
Found table for CLE in 2005.
Found table for ORL in 2005.
Found table for PHO in 2005.
Found table for DEN in 2005.
Found table for HOU in 2005.
Found table for MIN in 2005.
Found table for SAS in 2005.
Found table for POR in 2005.
Found table for SAC in 2005.
Page not found for CHH in 2005. Skipping...
Found table for DET in 2005.
Found table for DAL in 2005.
Found table for SEA in 2005.
Page not found for VAN in 2005. Skipping...
Found table for LAL in 2005.
Found table for LAC in 2005.
Found table for UTA in 2005.
Found table for WAS in 2005.
Found table for MIL in 2005.
Found table for MEM in 2005.
Found table for NOH in 2005.
Page not found for NOK in 2005. Skipping...
Page not found for OKC in 2005. Skipping...
Page not found for BRK in 2005. Skipping...
Page not found for NOP in 2005. Skipping...
Page not found for CHO in 2005. Skipping...
Found table for CHA in 2005.
Found table for MIA in 2006.
Found table for CHI in 2006.
Found table for PHI in 2006.
Found table for NJN in 2006.
Found table for GSW in 2006.
Found table for BOS in 2006.
Found table for IND in 2006.
Found table for ATL in 2006.
Found table for NYK in 2006.
Found table for TOR in 2006.
Found table for CLE in 2006.
Found table for ORL in 2006.
Found table for PHO in 2006.
Found table for DEN in 2006.
Found table for HOU in 2006.
Found table for MIN in 2006.
Found table for SAS in 2006.
Found table for POR in 2006.
Found table for SAC in 2006.
Page not found for CHH in 2006. Skipping...
Found table for DET in 2006.
Found table for DAL in 2006.
Found table for SEA in 2006.
Page not found for VAN in 2006. Skipping...
Found table for LAL in 2006.
Found table for LAC in 2006.
Found table for UTA in 2006.
Found table for WAS in 2006.
Found table for MIL in 2006.
Found table for MEM in 2006.
Page not found for NOH in 2006. Skipping...
Found table for NOK in 2006.
Page not found for OKC in 2006. Skipping...
Page not found for BRK in 2006. Skipping...
Page not found for NOP in 2006. Skipping...
Page not found for CHO in 2006. Skipping...
Found table for CHA in 2006.
Found table for MIA in 2007.
Found table for CHI in 2007.
Found table for PHI in 2007.
Found table for NJN in 2007.
Found table for GSW in 2007.
Found table for BOS in 2007.
Found table for IND in 2007.
Found table for ATL in 2007.
Found table for NYK in 2007.
Found table for TOR in 2007.
Found table for CLE in 2007.
Found table for ORL in 2007.
Found table for PHO in 2007.
Found table for DEN in 2007.
Found table for HOU in 2007.
Found table for MIN in 2007.
Found table for SAS in 2007.
Found table for POR in 2007.
Found table for SAC in 2007.
Page not found for CHH in 2007. Skipping...
Found table for DET in 2007.
Found table for DAL in 2007.
Found table for SEA in 2007.
Page not found for VAN in 2007. Skipping...
Found table for LAL in 2007.
Found table for LAC in 2007.
Found table for UTA in 2007.
Found table for WAS in 2007.
Found table for MIL in 2007.
Found table for MEM in 2007.
Page not found for NOH in 2007. Skipping...
Found table for NOK in 2007.
Page not found for OKC in 2007. Skipping...
Page not found for BRK in 2007. Skipping...
Page not found for NOP in 2007. Skipping...

Page not found for CHO in 2007. Skipping...
Found table for CHA in 2007.
Found table for MIA in 2008.
Found table for CHI in 2008.
Found table for PHI in 2008.
Found table for NJN in 2008.
Found table for GSW in 2008.
Found table for BOS in 2008.
Found table for IND in 2008.
Found table for ATL in 2008.
Found table for NYK in 2008.
Found table for TOR in 2008.
Found table for CLE in 2008.
Found table for ORL in 2008.
Found table for PHO in 2008.
Found table for DEN in 2008.
Found table for HOU in 2008.
Found table for MIN in 2008.
Found table for SAS in 2008.
Found table for POR in 2008.
Found table for SAC in 2008.
Page not found for CHH in 2008. Skipping...
Found table for DET in 2008.
Found table for DAL in 2008.
Found table for SEA in 2008.
Page not found for VAN in 2008. Skipping...
Found table for LAL in 2008.
Found table for LAC in 2008.
Found table for UTA in 2008.
Found table for WAS in 2008.
Found table for MIL in 2008.
Found table for MEM in 2008.
Found table for NOH in 2008.
Page not found for NOK in 2008. Skipping...
Page not found for OKC in 2008. Skipping...
Page not found for BRK in 2008. Skipping...
Page not found for NOP in 2008. Skipping...
Page not found for CHO in 2008. Skipping...
Found table for CHA in 2008.
Found table for MIA in 2009.
Found table for CHI in 2009.
Found table for PHI in 2009.
Found table for NJN in 2009.
Found table for GSW in 2009.
Found table for BOS in 2009.
Found table for IND in 2009.
Found table for ATL in 2009.
Found table for NYK in 2009.
Found table for TOR in 2009.
Found table for CLE in 2009.
Found table for ORL in 2009.
Found table for PHO in 2009.
Found table for DEN in 2009.
Found table for HOU in 2009.
Found table for MIN in 2009.
Found table for SAS in 2009.
Found table for POR in 2009.
Found table for SAC in 2009.
Page not found for CHH in 2009. Skipping...
Found table for DET in 2009.
Found table for DAL in 2009.
Page not found for SEA in 2009. Skipping...
Page not found for VAN in 2009. Skipping...
Found table for LAL in 2009.
Found table for LAC in 2009.
Found table for UTA in 2009.
Found table for WAS in 2009.
Found table for MIL in 2009.
Found table for MEM in 2009.
Found table for NOH in 2009.
Page not found for NOK in 2009. Skipping...
Found table for OKC in 2009.
Page not found for BRK in 2009. Skipping...
Page not found for NOP in 2009. Skipping...
Page not found for CHO in 2009. Skipping...
Found table for CHA in 2009.
Found table for MIA in 2010.
Found table for CHI in 2010.
Found table for PHI in 2010.
Found table for NJN in 2010.
Found table for GSW in 2010.
Found table for BOS in 2010.
Found table for IND in 2010.
Found table for ATL in 2010.
Found table for NYK in 2010.
Found table for TOR in 2010.
Found table for CLE in 2010.
Found table for ORL in 2010.
Found table for PHO in 2010.
Found table for DEN in 2010.
Found table for HOU in 2010.
Found table for MIN in 2010.
Found table for SAS in 2010.
Found table for POR in 2010.
Found table for SAC in 2010.
Page not found for CHH in 2010. Skipping...
Found table for DET in 2010.
Found table for DAL in 2010.
Page not found for SEA in 2010. Skipping...
Page not found for VAN in 2010. Skipping...
Found table for LAL in 2010.
Found table for LAC in 2010.
Found table for UTA in 2010.
Found table for WAS in 2010.
Found table for MIL in 2010.
Found table for MEM in 2010.
Found table for NOH in 2010.
Page not found for NOK in 2010. Skipping...
Found table for OKC in 2010.
Page not found for BRK in 2010. Skipping...
Page not found for NOP in 2010. Skipping...
Page not found for CHO in 2010. Skipping...
Found table for CHA in 2010.
Found table for MIA in 2011.
Found table for CHI in 2011.
Found table for PHI in 2011.
Found table for NJN in 2011.
Found table for GSW in 2011.
Found table for BOS in 2011.
Found table for IND in 2011.
Found table for ATL in 2011.
Found table for NYK in 2011.
Found table for TOR in 2011.
Found table for CLE in 2011.
Found table for ORL in 2011.
Found table for PHO in 2011.
Found table for DEN in 2011.
Found table for HOU in 2011.
Found table for MIN in 2011.
Found table for SAS in 2011.
Found table for POR in 2011.
Found table for SAC in 2011.
Page not found for CHH in 2011. Skipping...
Found table for DET in 2011.
Found table for DAL in 2011.
Page not found for SEA in 2011. Skipping...
Page not found for VAN in 2011. Skipping...
Found table for LAL in 2011.
Found table for LAC in 2011.
Found table for UTA in 2011.
Found table for WAS in 2011.
Found table for MIL in 2011.
Found table for MEM in 2011.
Found table for NOH in 2011.
Page not found for NOK in 2011. Skipping...
Found table for OKC in 2011.
Page not found for BRK in 2011. Skipping...
Page not found for NOP in 2011. Skipping...
Page not found for CHO in 2011. Skipping...
Found table for CHA in 2011.
Found table for MIA in 2012.
Found table for CHI in 2012.
Found table for PHI in 2012.
Found table for NJN in 2012.
Found table for GSW in 2012.
Found table for BOS in 2012.
Found table for IND in 2012.
Found table for ATL in 2012.
Found table for NYK in 2012.
Found table for TOR in 2012.
Found table for CLE in 2012.
Found table for ORL in 2012.
Found table for PHO in 2012.
Found table for DEN in 2012.
Found table for HOU in 2012.
Found table for MIN in 2012.
Found table for SAS in 2012.
Found table for POR in 2012.
Found table for SAC in 2012.
Page not found for CHH in 2012. Skipping...
Found table for DET in 2012.
Found table for DAL in 2012.
Page not found for SEA in 2012. Skipping...
Page not found for VAN in 2012. Skipping...
Found table for LAL in 2012.
Found table for LAC in 2012.
Found table for UTA in 2012.
Found table for WAS in 2012.
Found table for MIL in 2012.
Found table for MEM in 2012.
Found table for NOH in 2012.
Page not found for NOK in 2012. Skipping...
Found table for OKC in 2012.
Page not found for BRK in 2012. Skipping...
Page not found for NOP in 2012. Skipping...
Page not found for CHO in 2012. Skipping...
Found table for CHA in 2012.
Found table for MIA in 2013.
Found table for CHI in 2013.
Found table for PHI in 2013.
Page not found for NJN in 2013. Skipping...
Found table for GSW in 2013.
Found table for BOS in 2013.
Found table for IND in 2013.
Found table for ATL in 2013.
Found table for NYK in 2013.
Found table for TOR in 2013.
Found table for CLE in 2013.
Found table for ORL in 2013.
Found table for PHO in 2013.
Found table for DEN in 2013.
Found table for HOU in 2013.
Found table for MIN in 2013.
Found table for SAS in 2013.
Found table for POR in 2013.
Found table for SAC in 2013.
Page not found for CHH in 2013. Skipping...
Found table for DET in 2013.
Found table for DAL in 2013.
Page not found for SEA in 2013. Skipping...
Page not found for VAN in 2013. Skipping...
Found table for LAL in 2013.
Found table for LAC in 2013.
Found table for UTA in 2013.
Found table for WAS in 2013.
Found table for MIL in 2013.
Found table for MEM in 2013.
Found table for NOH in 2013.
Page not found for NOK in 2013. Skipping...
Found table for OKC in 2013.
Found table for BRK in 2013.
Page not found for NOP in 2013. Skipping...
Page not found for CHO in 2013. Skipping...
Found table for CHA in 2013.
Found table for MIA in 2014.
Found table for CHI in 2014.
Found table for PHI in 2014.
Page not found for NJN in 2014. Skipping...
Found table for GSW in 2014.
Found table for BOS in 2014.
Found table for IND in 2014.
Found table for ATL in 2014.
Found table for NYK in 2014.
Found table for TOR in 2014.
Found table for CLE in 2014.
Found table for ORL in 2014.
Found table for PHO in 2014.
Found table for DEN in 2014.
Found table for HOU in 2014.
Found table for MIN in 2014.
Found table for SAS in 2014.
Found table for POR in 2014.
Found table for SAC in 2014.
Page not found for CHH in 2014. Skipping...
Found table for DET in 2014.
Found table for DAL in 2014.
Page not found for SEA in 2014. Skipping...
Page not found for VAN in 2014. Skipping...
Found table for LAL in 2014.
Found table for LAC in 2014.
Found table for UTA in 2014.
Found table for WAS in 2014.
Found table for MIL in 2014.
Found table for MEM in 2014.
Page not found for NOH in 2014. Skipping...
Page not found for NOK in 2014. Skipping...
Found table for OKC in 2014.
Found table for BRK in 2014.

Found table for NOP in 2014.
Page not found for CHO in 2014. Skipping...
Found table for CHA in 2014.
Found table for MIA in 2015.
Found table for CHI in 2015.
Found table for PHI in 2015.
Page not found for NJN in 2015. Skipping...
Found table for GSW in 2015.
Found table for BOS in 2015.
Found table for IND in 2015.
Found table for ATL in 2015.
Found table for NYK in 2015.
Found table for TOR in 2015.
Found table for CLE in 2015.
Found table for ORL in 2015.
Found table for PHO in 2015.
Found table for DEN in 2015.
Found table for HOU in 2015.
Found table for MIN in 2015.
Found table for SAS in 2015.
Found table for POR in 2015.
Found table for SAC in 2015.
Page not found for CHH in 2015. Skipping...
Found table for DET in 2015.
Found table for DAL in 2015.
Page not found for SEA in 2015. Skipping...
Page not found for VAN in 2015. Skipping...
Found table for LAL in 2015.
Found table for LAC in 2015.
Found table for UTA in 2015.
Found table for WAS in 2015.
Found table for MIL in 2015.
Found table for MEM in 2015.
Page not found for NOH in 2015. Skipping...
Page not found for NOK in 2015. Skipping...
Found table for OKC in 2015.
Found table for BRK in 2015.
Found table for NOP in 2015.
Found table for CHO in 2015.
Page not found for CHA in 2015. Skipping...
Found table for MIA in 2016.
Found table for CHI in 2016.
Found table for PHI in 2016.
Page not found for NJN in 2016. Skipping...
Found table for GSW in 2016.
Found table for BOS in 2016.
Found table for IND in 2016.
Found table for ATL in 2016.
Found table for NYK in 2016.
Found table for TOR in 2016.
Found table for CLE in 2016.
Found table for ORL in 2016.
Found table for PHO in 2016.
Found table for DEN in 2016.
Found table for HOU in 2016.
Found table for MIN in 2016.
Found table for SAS in 2016.
Found table for POR in 2016.
Found table for SAC in 2016.
Page not found for CHH in 2016. Skipping...
Found table for DET in 2016.
Found table for DAL in 2016.
Page not found for SEA in 2016. Skipping...
Page not found for VAN in 2016. Skipping...
Found table for LAL in 2016.
Found table for LAC in 2016.
Found table for UTA in 2016.
Found table for WAS in 2016.
Found table for MIL in 2016.
Found table for MEM in 2016.
Page not found for NOH in 2016. Skipping...
Page not found for NOK in 2016. Skipping...
Found table for OKC in 2016.
Found table for BRK in 2016.
Found table for NOP in 2016.
Found table for CHO in 2016.
Page not found for CHA in 2016. Skipping...
Found table for MIA in 2017.
Found table for CHI in 2017.
Found table for PHI in 2017.
Page not found for NJN in 2017. Skipping...
Found table for GSW in 2017.
Found table for BOS in 2017.
Found table for IND in 2017.
Found table for ATL in 2017.
Found table for NYK in 2017.
Found table for TOR in 2017.
Found table for CLE in 2017.
Found table for ORL in 2017.
Found table for PHO in 2017.
Found table for DEN in 2017.
Found table for HOU in 2017.
Found table for MIN in 2017.
Found table for SAS in 2017.
Found table for POR in 2017.
Found table for SAC in 2017.
Page not found for CHH in 2017. Skipping...
Found table for DET in 2017.
Found table for DAL in 2017.
Page not found for SEA in 2017. Skipping...
Page not found for VAN in 2017. Skipping...
Found table for LAL in 2017.
Found table for LAC in 2017.
Found table for UTA in 2017.
Found table for WAS in 2017.
Found table for MIL in 2017.
Found table for MEM in 2017.
Page not found for NOH in 2017. Skipping...
Page not found for NOK in 2017. Skipping...
Found table for OKC in 2017.
Found table for BRK in 2017.
Found table for NOP in 2017.
Found table for CHO in 2017.
Page not found for CHA in 2017. Skipping...
Found table for MIA in 2018.
Found table for CHI in 2018.
Found table for PHI in 2018.
Page not found for NJN in 2018. Skipping...
Found table for GSW in 2018.
Found table for BOS in 2018.
Found table for IND in 2018.
Found table for ATL in 2018.
Found table for NYK in 2018.
Found table for TOR in 2018.
Found table for CLE in 2018.
Found table for ORL in 2018.
Found table for PHO in 2018.
Found table for DEN in 2018.
Found table for HOU in 2018.
Found table for MIN in 2018.
Found table for SAS in 2018.
Found table for POR in 2018.
Found table for SAC in 2018.
Page not found for CHH in 2018. Skipping...
Found table for DET in 2018.
Found table for DAL in 2018.
Page not found for SEA in 2018. Skipping...
Page not found for VAN in 2018. Skipping...
Found table for LAL in 2018.
Found table for LAC in 2018.
Found table for UTA in 2018.
Found table for WAS in 2018.
Found table for MIL in 2018.
Found table for MEM in 2018.
Page not found for NOH in 2018. Skipping...
Page not found for NOK in 2018. Skipping...
Found table for OKC in 2018.
Found table for BRK in 2018.
Found table for NOP in 2018.
Found table for CHO in 2018.
Page not found for CHA in 2018. Skipping...
Found table for MIA in 2019.
Found table for CHI in 2019.
Found table for PHI in 2019.
Page not found for NJN in 2019. Skipping...
Found table for GSW in 2019.
Found table for BOS in 2019.
Found table for IND in 2019.
Found table for ATL in 2019.
Found table for NYK in 2019.
Found table for TOR in 2019.
Found table for CLE in 2019.
Found table for ORL in 2019.
Found table for PHO in 2019.
Found table for DEN in 2019.
Found table for HOU in 2019.
Found table for MIN in 2019.
Found table for SAS in 2019.
Found table for POR in 2019.
Found table for SAC in 2019.
Page not found for CHH in 2019. Skipping...
Found table for DET in 2019.
Found table for DAL in 2019.
Page not found for SEA in 2019. Skipping...
Page not found for VAN in 2019. Skipping...
Found table for LAL in 2019.
Found table for LAC in 2019.
Found table for UTA in 2019.
Found table for WAS in 2019.
Found table for MIL in 2019.
Found table for MEM in 2019.
Page not found for NOH in 2019. Skipping...
Page not found for NOK in 2019. Skipping...
Found table for OKC in 2019.
Found table for BRK in 2019.
Found table for NOP in 2019.
Found table for CHO in 2019.
Page not found for CHA in 2019. Skipping...
Found table for MIA in 2020.
Found table for CHI in 2020.
Found table for PHI in 2020.
Page not found for NJN in 2020. Skipping...
Found table for GSW in 2020.
Found table for BOS in 2020.
Found table for IND in 2020.
Found table for ATL in 2020.
Found table for NYK in 2020.
Found table for TOR in 2020.
Found table for CLE in 2020.
Found table for ORL in 2020.
Found table for PHO in 2020.
Found table for DEN in 2020.
Found table for HOU in 2020.
Found table for MIN in 2020.
Found table for SAS in 2020.
Found table for POR in 2020.
Found table for SAC in 2020.
Page not found for CHH in 2020. Skipping...
Found table for DET in 2020.
Found table for DAL in 2020.
Page not found for SEA in 2020. Skipping...
Page not found for VAN in 2020. Skipping...
Found table for LAL in 2020.
Found table for LAC in 2020.
Found table for UTA in 2020.
Found table for WAS in 2020.
Found table for MIL in 2020.
Found table for MEM in 2020.
Page not found for NOH in 2020. Skipping...
Page not found for NOK in 2020. Skipping...
Found table for OKC in 2020.
Found table for BRK in 2020.
Found table for NOP in 2020.
Found table for CHO in 2020.
Page not found for CHA in 2020. Skipping...
Found table for MIA in 2021.
Found table for CHI in 2021.
Found table for PHI in 2021.
Page not found for NJN in 2021. Skipping...
Found table for GSW in 2021.
Found table for BOS in 2021.
Found table for IND in 2021.
Found table for ATL in 2021.
Found table for NYK in 2021.
Found table for TOR in 2021.
Found table for CLE in 2021.
Found table for ORL in 2021.
Found table for PHO in 2021.
Found table for DEN in 2021.
Found table for HOU in 2021.
Found table for MIN in 2021.
Found table for SAS in 2021.
Found table for POR in 2021.
Found table for SAC in 2021.
Page not found for CHH in 2021. Skipping...
Found table for DET in 2021.
Found table for DAL in 2021.
Page not found for SEA in 2021. Skipping...
Page not found for VAN in 2021. Skipping...
Found table for LAL in 2021.
Found table for LAC in 2021.
Found table for UTA in 2021.
Found table for WAS in 2021.
Found table for MIL in 2021.
Found table for MEM in 2021.
Page not found for NOH in 2021. Skipping...
Page not found for NOK in 2021. Skipping...
Found table for OKC in 2021.

Found table for BRK in 2021.
Found table for NOP in 2021.
Found table for CHO in 2021.
Page not found for CHA in 2021. Skipping...
Found table for MIA in 2022.
Found table for CHI in 2022.
Found table for PHI in 2022.
Page not found for NJN in 2022. Skipping...
Found table for GSW in 2022.
Found table for BOS in 2022.
Found table for IND in 2022.
Found table for ATL in 2022.
Found table for NYK in 2022.
Found table for TOR in 2022.
Found table for CLE in 2022.
Found table for ORL in 2022.
Found table for PHO in 2022.
Found table for DEN in 2022.
Found table for HOU in 2022.
Found table for MIN in 2022.
Found table for SAS in 2022.
Found table for POR in 2022.
Found table for SAC in 2022.
Page not found for CHH in 2022. Skipping...
Found table for DET in 2022.
Found table for DAL in 2022.
Page not found for SEA in 2022. Skipping...
Page not found for VAN in 2022. Skipping...
Found table for LAL in 2022.
Found table for LAC in 2022.
Found table for UTA in 2022.
Found table for WAS in 2022.
Found table for MIL in 2022.
Found table for MEM in 2022.
Page not found for NOH in 2022. Skipping...
Page not found for NOK in 2022. Skipping...
Found table for OKC in 2022.
Found table for BRK in 2022.
Found table for NOP in 2022.
Found table for CHO in 2022.
Page not found for CHA in 2022. Skipping...
Found table for MIA in 2023.
Found table for CHI in 2023.
Found table for PHI in 2023.
Page not found for NJN in 2023. Skipping...
Found table for GSW in 2023.
Found table for BOS in 2023.
Found table for IND in 2023.
Found table for ATL in 2023.
Found table for NYK in 2023.
Found table for TOR in 2023.
Found table for CLE in 2023.
Found table for ORL in 2023.
Found table for PHO in 2023.
Found table for DEN in 2023.
Found table for HOU in 2023.
Found table for MIN in 2023.
Found table for SAS in 2023.
Found table for POR in 2023.
Found table for SAC in 2023.
Page not found for CHH in 2023. Skipping...
Found table for DET in 2023.
Found table for DAL in 2023.
Page not found for SEA in 2023. Skipping...
Page not found for VAN in 2023. Skipping...
Found table for LAL in 2023.
Found table for LAC in 2023.
Found table for UTA in 2023.
Found table for WAS in 2023.
Found table for MIL in 2023.
Found table for MEM in 2023.
Page not found for NOH in 2023. Skipping...
Page not found for NOK in 2023. Skipping...
Found table for OKC in 2023.
Found table for BRK in 2023.
Found table for NOP in 2023.
Found table for CHO in 2023.
Page not found for CHA in 2023. Skipping...
Found table for MIA in 2024.
Found table for CHI in 2024.
Found table for PHI in 2024.
Page not found for NJN in 2024. Skipping...
Found table for GSW in 2024.
Found table for BOS in 2024.
Found table for IND in 2024.
Found table for ATL in 2024.
Found table for NYK in 2024.
Found table for TOR in 2024.
Found table for CLE in 2024.
Found table for ORL in 2024.
Found table for PHO in 2024.
Found table for DEN in 2024.
Found table for HOU in 2024.
Found table for MIN in 2024.
Found table for SAS in 2024.
Found table for POR in 2024.
Found table for SAC in 2024.
Page not found for CHH in 2024. Skipping...
Found table for DET in 2024.
Found table for DAL in 2024.
Page not found for SEA in 2024. Skipping...
Page not found for VAN in 2024. Skipping...
Found table for LAL in 2024.
Found table for LAC in 2024.
Found table for UTA in 2024.
Found table for WAS in 2024.
Found table for MIL in 2024.
Found table for MEM in 2024.
Page not found for NOH in 2024. Skipping...
Page not found for NOK in 2024. Skipping...
Found table for OKC in 2024.
Found table for BRK in 2024.
Found table for NOP in 2024.
Found table for CHO in 2024.
Page not found for CHA in 2024. Skipping...

In [12]:
for team, df in game_log_dfs.items():
    season = team[:4]
    df['Opponent'] = df['Opponent'].map(nba_teams)
    df['Opponent'] = df['Opponent'].apply(lambda x: season + x)

In [13]:
game_log_dfs['2002HOU']

   Opponent Result
0   2002ATL      W
1   2002LAC      W
2   2002MIN      L
3   2002PHO      W
4   2002DEN      W
..      ...    ...
80  2002DAL      W
81  2002POR      L
82  2002MEM      L
84  2002DEN      L
85  2002POR      L

[82 rows x 2 columns]

In [10]:
ex = game_log_dfs['2002HOU'].copy()
ex

                  Opponent Result
0            Atlanta Hawks      W
1     Los Angeles Clippers      W
2   Minnesota Timberwolves      L
3             Phoenix Suns      W
4           Denver Nuggets      W
..                     ...    ...
80        Dallas Mavericks      W
81  Portland Trail Blazers      L
82       Memphis Grizzlies      L
84          Denver Nuggets      L
85  Portland Trail Blazers      L

[82 rows x 2 columns]

In [14]:
%store game_log_dfs

Stored 'game_log_dfs' (dict)

In [19]:
le_df = pd.read_csv(r"C:\Users\vaugh\Desktop\basketball-pf-research\Important DataFrames\height_histograms_le_df.csv")

In [20]:
trendy_teams = []
untrendy_teams = []
for season in le_df['Season'].unique():
    not_trend = list(le_df[le_df['Season'] == season].nlargest(5, 'Distance').get('Roster'))
    trend = list(le_df[le_df['Season'] == season].nsmallest(5, 'Distance').get('Roster'))
    trendy_teams.extend(trend)
    untrendy_teams.extend(not_trend)

In [115]:
team_performance_dfs = {}

def categorize_opponent(opponent):
    if opponent in trendy_teams:
        return 'trendy'
    elif opponent in untrendy_teams:
        return 'not-trendy'
    else:
        return 'neither'
    
for team, df in game_log_dfs.items():
    df = df.copy()
    season = team[:4]
    df['Opponent'] = df['Opponent'].map(nba_teams)
    df['Opponent'] = df['Opponent'].apply(lambda x: season + x)
    df['Opponent Type'] = df['Opponent'].apply(categorize_opponent)
    df['Result'] = df['Result'].map({'W': 1, 'L': 0})
    df = df.groupby('Opponent Type').mean(numeric_only=True)
    team_performance_dfs[team] = df

In [130]:
team_performance_dfs['2001MIA']

                 Result
Opponent Type
neither        0.577778
not-trendy     0.562500
trendy         0.714286

In [134]:
transformed_dfs = []

for team, df in team_performance_dfs.items():
    transformed_df = pd.DataFrame({
        'Roster': [team],
        'Trendy': [df.loc['trendy', 'Result']],
        'Not-Trendy': [df.loc['not-trendy', 'Result']],
        'Neither': [df.loc['neither', 'Result']]
    })
    transformed_dfs.append(transformed_df)

# Combine all transformed DataFrames
final_df = pd.concat(transformed_dfs, ignore_index=True)

In [135]:
final_df

      Roster    Trendy  Not-Trendy   Neither
0    2001MIA  0.714286    0.562500  0.577778
1    2001CHI  0.266667    0.222222  0.142857
2    2001PHI  0.900000    0.750000  0.580000
3    2001NJN  0.368421    0.333333  0.288889
4    2001GSW  0.300000    0.166667  0.200000
..       ...       ...         ...       ...
711  2024MEM  0.307692    0.230769  0.357143
712  2024OKC  0.800000    0.571429  0.706897
713  2024BRK  0.545455    0.312500  0.381818
714  2024NOP  0.461538    0.428571  0.666667
715  2024CHO  0.133333    0.266667  0.288462

[716 rows x 4 columns]